name: Delivery

on:
  workflow_run:
    workflows: ["Integration"]
    types:
      - completed

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest
        
      - name: Download Dear ImGui Source
        run: |
          git clone --depth 1 https://github.com/ocornut/imgui.git imgui

      - name: Compile application
        run: |
          g++ -I./imgui/ -I./imgui/backends/ -I./include/ILiDiS/ -I./tests source/main.cpp source/gui.cpp source/winctrl.cpp source/texturectrl.cpp tests/workflow.cpp ./imgui/imgui.cpp ./imgui/imgui_draw.cpp ./imgui/imgui_tables.cpp ./imgui/imgui_widgets.cpp ./imgui/backends/imgui_impl_dx11.cpp ./imgui/backends/imgui_impl_win32.cpp -o program.exe -ld3d11 -ld3dcompiler -lgdi32 -ldwmapi -lole32 -luuid
        
    
      - name: Release new version
        shell: bash
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(gh release list --limit 1 | awk -F'\t' '{print $3}')
          
          if [ -z "$LATEST_TAG" ]; then
            # Initial fallback if no releases exist
            NEXT_TAG="v1.0"
          else
            CURRENT_PATCH=$(echo "$LATEST_TAG" | sed -E 's/^v1\.//')
            
            NEXT_PATCH=$((CURRENT_PATCH + 1))
            NEXT_TAG="v1.$NEXT_PATCH"
          fi
          gh release create $NEXT_TAG program.exe --title "UPTYRE_ILiDiS ${{ github.ref_name }}" --notes "Build generated by automated workflow."
    
