name: Delivery

on:
  workflow_run:
    workflows: ["Integration"]
    types:
      - completed

jobs:
  release:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest
        
      - name: Download Dear ImGui Source
        run: |
          git clone --depth 1 https://github.com/ocornut/imgui.git imgui

      - name: Compile application
        run: |
          g++ -I./imgui/ -I./imgui/backends/ -I./include/ILiDiS/ -I./tests source/main.cpp source/gui.cpp source/winctrl.cpp tests/workflow.cpp ./imgui/imgui.cpp ./imgui/imgui_draw.cpp ./imgui/imgui_tables.cpp ./imgui/imgui_widgets.cpp ./imgui/backends/imgui_impl_dx11.cpp ./imgui/backends/imgui_impl_win32.cpp -o program.exe -ld3d11 -ld3dcompiler -lgdi32 -ldwmapi -lole32 -luuid
        
    
      - name: Release new version
        run: |
          gh release create ${{ github.ref_name }} program.exe -- "Release ${{ github.ref_name }}" --notes "Build generated by automated workflow."
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
